### ISSUE TITLE
Joal-Desktop v2.0.8 stucks on start - MacOs

### ISSUE THREAD

**Issue by luccios** [anthonyraymond/joal-desktop#62]
Hi
Thanks for your software :)

I need help with my connection. 
I can open Joal-Desktop v2.0.8 without a VPN, but with a VPN enabled it stucks on start.

I am running Mac OS 10.14.6 and I didn't find these files :
~/.config/JoalDesktop/jre directory
~/.config/JoalDesktop/joal-core directory
(Still, I can access ~/.config/JoalDesktop)

Also, I don't understand how to implement the "run the appimage from a console" solution.

Can you help?

**Comment by anthonyraymond** [comment]
Hello @luccios 

What do you mean by stuck on start? Can you share a screenshot so i can get an idea of when it's going bad pelase?

**Comment by luccios** [comment]
Sure ! It doesn't go past this screen
![Capture d’écran 2021-11-20 à 23 29 42](https://user-images.githubusercontent.com/22468454/142742649-0335ade7-42ef-4b35-bfc0-3b232df16fc2.png)
 :

**Comment by Oneloutre** [comment]
Yep, I've got the same issue :/

**Comment by Oneloutre** [comment]
> Hi Thanks for your software :)
> 
> I need help with my connection. I can open Joal-Desktop v2.0.8 without a VPN, but with a VPN enabled it stucks on start.
> 
> I am running Mac OS 10.14.6 and I didn't find these files : ~/.config/JoalDesktop/jre directory ~/.config/JoalDesktop/joal-core directory (Still, I can access ~/.config/JoalDesktop)
> 
> Also, I don't understand how to implement the "run the appimage from a console" solution.
> 
> Can you help?

Okay, finally I rebooted my mac and it works, maybe should u do that ?

**Comment by anthonyraymond** [comment]
Hard reboot is a way to solve this most of the time. It's a known issue with Mac not closing reosurces properly on exit

**Comment by luccios** [comment]
I already mentioned that it works fine without VPN but it does not open when VPN is launched. Do you have any other ideas?

**Comment by anthonyraymond** [comment]
Can i know who is yout VPN provider? Alos, are you using the provider specific app or OpenVpn?

**Comment by luccios** [comment]
Sure : PureVPN v8.4.1 app

**Comment by anthonyraymond** [comment]
Can you please try with version 2.0.9 i just released?
You'll need to fully close joal desktop before upgrading (i suggest reboot because mac is a bit tricky to fully close an app)

**Comment by luccios** [comment]
Hello,
Thank you for taking the time to help solve my problem. I appreciate your efforts in trying to find a solution. Unfortunately, I am still experiencing the same issue. I hope you can continue to help me solve it. Kind regards.

**Comment by sbucaille** [comment]
Hey guys, got the same issue by being stuck on the update screen. You mention rebooting macos because it doesn't fully close all resources, but I tried shutting java off in the activity monitor and it worked. So I guess no need to completely reboot your computer (I definitely didn't want to do that personally ahha)

**Comment by Oneloutre** [comment]
Yep, u definitely don't need to reboot the entire computer, just to stop the java process (using the pid is possible too)

**Comment by anthonyraymond** [comment]
Indeed, stopping the java process works.
Bur rebooting is a much simplier solution, that's why i said so.

**Comment by Oneloutre** [comment]
for me it feels like killing a mosquito with a bazooka 😂

**Comment by anthonyraymond** [comment]
Sometime the bazooka is easier to use than the sniper rifle 😆

**Comment by remiflament** [comment]
> For me killing Java didn't work. What worked is killing the right `JoalDesktop Helper` process when it's stuck on the updates screen.

Same resolution for me...
Hope they find a fix 🙏

**Comment by anthonyraymond** [comment]
Do you need to restart Joal after killing "JoalDesktop Helper" ? Or just killing it is enough to "unstuck" the situation?

**Comment by remiflament** [comment]
> Do you need to restart Joal after killing "JoalDesktop Helper" ? Or just killing it is enough to "unstuck" the situation?

I'm sorry for the late response, didn't catch the notification...

I remembered to restart it after killing the bad process.
